### ISSUE TITLE
python3 Question

### ISSUE THREAD

**Issue by kmolLin** [lbl-srg/BuildingsPy#169]
Did this project support for python3 or can use pip3 install 
Thank you a lot

**Comment by thorade** [comment]
Python 3 support was added by issue #94 and related pull requests. 
There has not been a new [release to PyPi](https://pypi.python.org/pypi/buildingspy) since then, 
so Python 3 users currently have to use the latest master. 
pip can install directly from a git repository, the [recommended command](https://docs.python.org/3/installing/#work-with-multiple-versions-of-python-installed-in-parallel) is:
```
python -m pip install --upgrade git+https://github.com/lbl-srg/BuildingsPy@master
```

If that works for you, please report it here and close the issue, thanks.

**Comment by kmolLin** [comment]
Sorry I have a stupid question , did i need to install Dymola to do simulation.
I well test 1.6 version few time. When works perfect I will report 
Thx~ you reply

**Comment by thorade** [comment]
Yes, you need Dymola to do the simulation. Buildingspy just calls Dymola and e.g. sets some parameters. Alternatively, you could also use Dymolas Python interface or OMPython with OpenModelica.
There are some more packages, just search PyPi for Modelica:
https://pypi.python.org/pypi?%3Aaction=search&term=modelica&submit=search

**Comment by thorade** [comment]
And another comment: There is a demo version of Dymola available, but currently only for Windows:
https://www.3ds.com/products-services/catia/products/dymola/latest-release/
The Linux version is available upon request only. 

Installation instructions are then either in the Dymola manual, or here:
http://simulationresearch.lbl.gov/modelica/installDymolaLinux.html
https://github.com/UdK-VPT/BuildingSystems/wiki/Dymola-on-Ubuntu

**Comment by kmolLin** [comment]
can use the BuildingsPy to read the modelica standard-library (.mo) and simulation by Dymola ? or there have another OpenSource solver.
I want build like Pysimulation GUI and it can input different signal.

**Comment by thorade** [comment]
Buildingspy itself does not parse or simulate the Modelica code, it just calls a simulation tool (Dymola, OpenModelica or JModelica). The simulation tool runs the simulation, and buildingspy can then read the results and do some plotting.

Here are some links that might be helpful, but I am not 100% sure I understood what you want achieve.

- https://modelica.org/tools
- https://github.com/OpenModelica/OMPython
- https://openmodelica.org/
- https://build.openmodelica.org/Documentation/OpenModelica.Scripting.html
- http://jmodelica.org/page/69
- https://github.com/mbonvini/ModelicaInAction
- https://github.com/xie-dongping/modparc
- https://github.com/PySimulator/PySimulator
- https://github.com/CATIA-Systems/FMPy
- http://jmodelica.org/page/4924

**Comment by kmolLin** [comment]
Sorry I did't expression my program .
I want load (.mo) or FMI files and simulate it to draw plot and return value for checking my signal .
Just like Jmodelica to use pyfmi to simulate but it's use python2.7. 
I need to use python3 to write my program
Thank you a lot for help me.

**Comment by thorade** [comment]
I think Buildingspy uses Dymola to interact with FMI files, allthough it would be possible to interact directly (as done by e.g. pyFMI and FMPy).
I think I heard that pyFMI works on python3, maybe you can just install it and see if it works?
Alternatively, try FMPy, that supports py3 for sure.

You will still need some tool to translate the Modelica code into an FMI, like Dymola or OpenModelica. And both also have a Python interface, so if you do not need the features of FMI, you could as well just use the Python interface.

Do you have a Dymola license? If not, I would recommend you install OpenModelica (because it is easier to install than JModelica). Then try OMPython to parameterize and start your simulation, or use OMPython to translate to FMI and then use one of the FMI tools to interact with the FMI.
The results might be written to a .mat file, you can use DyMat to read that file, and then you can just use matplotlib or whatever you want.

**Comment by kmolLin** [comment]
The pyFMI I have try but I'm not sure the it support python3 yet!
And FMpy can load .fmu with python3 I have test.
I have a quedtion is that use openmodelica ompython need to open the openmodelica program ?
where will solve the program in this process.

**Comment by thorade** [comment]
OMPython talks to OMC, the OpenModelica compiler. Similar for the Dymola Python interface, it sends commands to the Dymola compiler and receives results back.

The Python part is a just a thin wrapper or interface, all the difficult tasks like translating Modelica code into an executable are done by OMC or Dymola.

The Python part can do the same what you can do by clicking a button in the GUI, you just send a command to the compiler.

**Comment by kmolLin** [comment]
If i want to use the OpenModelica , I need to install list below right ?

First I need to install OpenModelica compile not edit right ?
Second prepare OMpython interface use ZMQ to get communication with OpenModelica.
Third Maybe can write modelica model by self and compile it to fml or show right ?

Should I compile OpenModelica compile ?

**Comment by thorade** [comment]
What operating system do you use? Windows? Linux? Ubuntu?

You should install OpenModelica, following the instructions on their homepage:
https://openmodelica.org/
That will also install OMEdit, a graphical editor. From OMEdit you can test whether your installation works and already compile/execute example models from the Modelica standard library or export them to FMU.

When you have that part working, you should 
- install FMPy and test whether you can interact with the exported FMU. 
- Then, install OMPython and try to start a simulation and read the results, 
- and/or try to automate the FMU export.

Good luck! 

For further questions I recommend you try 
- the [OpenModelica forum](https://openmodelica.org/forum), 
- [stackoverflow](https://stackoverflow.com/questions/tagged/modelica), 
- or the [FMPy issue tracker](https://github.com/CATIA-Systems/FMPy/issues).
