### ISSUE TITLE
unit tests do not finish when dymola suggests code change

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/BuildingsPy#219]
In some cases the unit tests do not finish and python hence does not report results. If I use `_showGUI=True` then I get 

```
...
Modelica.Utilities.Streams.print("      }", "statistics.json");
Modelica.Utilities.Streams.print("    }", "statistics.json")
Modelica.Utilities.Streams.print("  ]", "statistics.json")
Modelica.Utilities.Streams.print("}", "statistics.json")
Modelica.Utilities.System.exit();
Undeclared function Modelica.Utilities.System.exit.
 = false
```
in 2 of my 12 dymola processes.

If I then manually retype `Modelica.Utilities.System.exit();` it does work, but I get a dialog box that asks to save some changes that dymola made to the code automatically before dymola actually closes. That's probably related. One solution is to change the code such that the underlying code problem is resolved, but this is quite cumbersome to debug. Travis somehow does not have this problem and terminates correctly.

Any suggestions on improving this?

**Comment by mwetter** [comment]
I am not aware of a setting that automatically exits dymola if there is an error. However, if you update your BuildingsPy, then you don't get the `Undeclared function Modelica.Utilities.System.exit` because it simply calls exit rather than using the Dymola function. This change was required to test MSL 3.2.3 beta1

**Comment by Mathadon** [comment]
cool
