### ISSUE TITLE
Update merge script for HeatPumps documentation

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/BuildingsPy#223]
This is to update the merge script due to the addition of the HeatPumps package that has Python code and documentation in which the library name needs to be replaced.

**Comment by mwetter** [comment]
This is on the master.

**Comment by thorade** [comment]
Not sure if I did something wrong, but merging still failed for me with utf8 related problems due to files in this directory:
https://github.com/ibpsa/modelica-ibpsa/tree/master/IBPSA/Resources/src/fluid/heatpumps/calibration/doc
I also re-installed buildingspy from master, but that did not solve it.
For now, I just deleted that folder locally. For the future, I will report if the problem persists.
