### ISSUE TITLE
allow simulation without recompilation

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/BuildingsPy#70]
This issue is for integrating and testing
https://github.com/lbl-srg/BuildingsPy/pull/69

**Comment by mwetter** [comment]
Todo:
 - [ ] Check why `runSimulationTranslated.py` uses the protected function `_deleteTemporaryDirectory`
 - [ ] Add regression test that attempts to change a parameter that was evaluated at compile time, and hence `simulate_translated` should throw an exception.

**Comment by mwetter** [comment]
@mrosemeier : I added the regression test `buildingspy.tests.test_translate_simulate_exception` that translates a model and changes a parameter which is fixed at compilation time (because it is used to compute and assign the size of a vector).
The test should fail, but it simply computes the old model with no error message.
Can you build in some tests to catch this situation? Otherwise, users may change (multiple) parameters, simulate a model, but not notice that some parameter changes had no effect.

This is why I think, unless such a test is added, users may be better of if they export a model as an FMU and then change the parameters at which point a tool can check whether the value can be changed.

**Comment by mrosemeier** [comment]
@mwetter : I have added a test that catches the situation (see pull request).

So far, I could not check out the benefits of FMUs since I get compilation errors in liblapack with my models/ system.

**Comment by mwetter** [comment]
@mrosemeier 
Thanks for the latest pull request. 

I have a few questions/comments:
 - [ ] I wonder why there is a file `fullRobot.mat` in `buildingspy/examples/dymola/case1/.gitignore` and `buildingspy/examples/dymola/case1/.gitignore`? There is no file `fullRobot.mat` in the repository (and there shouldn't be), so this line should be removed from`.gitignore`.

 - [ ] The following command fails with `IOError: [Errno 2] No such file or directory: './myModel.mat'`. 
(These commands are also executed with `make doctest`.)
```
from buildingspy.simulate.Simulator import Simulator
s=Simulator("myPackage.myModel", "dymola", packagePath="buildingspy/tests/MyModelicaLibrary")
s.translate()
s.simulate_translated()
```

**Comment by mrosemeier** [comment]
@mwetter 

- [x]  I wonder why there is a file `fullRobot.mat` in `buildingspy/examples/dymola/case1/.gitignore` and `buildingspy/examples/dymola/case1/.gitignore`? There is no file `fullRobot.mat` in the repository (and there shouldn't be), so this line should be removed from `.gitignore`.
 - The example I have had given in  `buildingspy/examples/dymola/runSimulationTranslated` uses the `fullRobot`. Now, I have adpated it to the standard example from Buildings.

- [x] The following command fails with `IOError: [Errno 2] No such file or directory: './myModel.mat'`.
In general the `IOError` is thrown correctly since the simulation was not succesful (`simulateModel() = false`) and no `.mat` file was written. However, there were several problems in the snippet:
 - It is pointing to a non-existing library path. The actual model is in `"MyModelicaLibrary.MyModel"`. I think a test is required to capture this.
 - The simulation for this model runs only with a model redeclaration `"redeclare Modelica.Blocks.Sources.Step source(offset=-0.1, height=1.1, startTime=0.5)"`. I think a test is required to capture this. Do you have any idea how to capture this?
 - The solver needs to be set to `"dassl"` since the standard set in Simulator is  `"radau"`.
 - To remove the temporary translation directory it is recommended to add `s.deleteTranslateDirectory()`

I have adpated the docs in Simulator according to the following example. Also `make doctest` does not give an error.
```
from buildingspy.simulate.Simulator import Simulator
s = Simulator("MyModelicaLibrary.MyModel", "dymola", packagePath="buildingspy/tests/MyModelicaLibrary")
s.addModelModifier("redeclare Modelica.Blocks.Sources.Step source(offset=-0.1, height=1.1, startTime=0.5)")
s.setSolver("dassl")
s.translate()
s.simulate_translated()
s.deleteTranslateDirectory()
```

**Comment by mwetter** [comment]
@mrosemeier 
The regression tests still fail. To reproduce, run `make unittest`. I commented most of the regression tests except the ones that use the simulation. The failure is in `test_translate_simulate()` and the output of dymola is
```
RunScript("/opt/dymola/insert/dymola.mos", true);
 = true
 = true
RunScript("/home/mwetter/.dynasim/setup.mos", true);
 = true
RunScript("/tmp/tmp-simulator-mwetter-FDiAb5/MyModelicaLibrary/run_simulate.mos");
// File autogenerated
// Do not edit.
cd("/tmp/tmp-simulator-mwetter-FDiAb5/MyModelicaLibrary");
/tmp/tmp-simulator-mwetter-FDiAb5/MyModelicaLibrary
 = true
Modelica.Utilities.Files.remove("simulator.log");
OutputCPUtime:=true;
resultFile="myResults";
Declaring variable: String resultFile ;
simulateModel("", startTime=-1, stopTime=5, method="dassl", tolerance=0.0001, resultFile="myResults", numberOfIntervals=50);
 = false
simulate();
Finished
 = true
system("mv dsres.mat myResults.mat");
 = true
savelog("simulator.log");
```
Hence, the command `simulateModel("", startTime=-1, stopTime=5, method="dassl", tolerance=0.0001, resultFile="myResults", numberOfIntervals=50);` fails. The command `simulate()` produces a new output file, but it does not take any arguments and hence cannot be used to change parameter values. I therefore do not see how we could implement running the model twice with different parameter values.

**Comment by mrosemeier** [comment]
@mwetter 
The `simulateModel()` function is used here to re-set solely the simulation parameters `startTime`, `stopTime`, etc. This is necessary since dymola does not know the simulation parameters when it's reloading a translated model. `simulateModel()` is not used to actually simulate the model. That's why it returns `false`. `simulate()` then runs the simulation.
Parameters that should be changed are overridden before.

The best way to show this functionality is to run `buildingspy/examples/dymola/runsSimulationTranslated.py`. Here, the parameter `con.eOn` is changed for both cases. The dymola output for `case1` is:
```
RunScript("/opt/dymola-2016-x86_64/insert/dymola.mos", true);
 = true
 = true
RunScript("/home/mrosemeier/.dynasim/setup.mos", true);
 = true
RunScript("/tmp/tmp-simulator-mrosemeier-iVpyJR/dymola/run_simulate.mos");
// File autogenerated
// Do not edit.
cd("/tmp/tmp-simulator-mrosemeier-iVpyJR/dymola");
/tmp/tmp-simulator-mrosemeier-iVpyJR/dymola
 = true
Modelica.Utilities.Files.remove("simulator.log");
OutputCPUtime:=true;
con.eOn=0.1;
resultFile="PIDHysteresis";
Declaring variable: String resultFile ;
simulateModel("", startTime=0, stopTime=86400, method="dassl", tolerance=1e-06, resultFile="PIDHysteresis");
 = false
simulate();
Finished
 = true
system("mv dsres.mat PIDHysteresis.mat");
 = true
savelog("simulator.log");
```

This might not be a proper solution but it works. However, I am open to other suggestions.

**Comment by mwetter** [comment]
@mrosemeier 
I refactored the unit tests, added some additional tests and cleaned up the code. Your contribution is now working and passes all the regression tests. I merged it into the `master` branch.
Thanks for your contribution.

**Comment by mrosemeier** [comment]
@mwetter 
Thanks for merging! I really appreciate it.
